version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=dev
      - DIR_DATA=data
      - GCP_PROJECT_ID=suzuito-minilla
      - GCP_BUCKET_ARTICLE=suzuito-minilla-blog1-article
      - ALLOWED_ORIGINS=http://localhost:4200,http://localhost:8080
      - ALLOWED_METHODS=GET,POST,DELETE
      - GOOGLE_APPLICATION_CREDENTIALS=./application_default_credentials.json
      - DIR_PATH_TEMPLATE=data/template
      - DIR_PATH_CSS=data/css
      - DIR_PATH_ASSET=data/asset
      - SITE_ORIGIN=http://localhost:8080
      - GA=
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    command: /bin/bash -c 'air -c .air.server.toml'
    ports:
      - 8080:8080
  gcf:
    build:
      context: .
      dockerfile: gcf.Dockerfile
    environment:
      - ENV=dev
      - GCP_PROJECT_ID=suzuito-minilla
      - GCP_BUCKET_ARTICLE=suzuito-minilla-blog1-article
      - GOOGLE_APPLICATION_CREDENTIALS=./application_default_credentials.json
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    command: /bin/bash -c 'air -c .air.gcf.toml'
