apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blog1-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - image: gcr.io/suzuito-minilla/blog1-api:latest
        resources:
          limits:
            memory: 256Mi
            cpu: 1000m
        env:
        - name: GCP_PROJECT_ID
          value: suzuito-minilla
        - name: GCP_BUCKET_ARTICLE
          value: suzuito-minilla-blog1-article
        - name: ENV
          value: minilla
        - name: ALLOWED_ORIGINS
          value: https://minilla-blog.tach.dev,http://localhost:4200,http://localhost:8080,http://server:8080
        - name: ALLOWED_METHODS
          value: GET,PUT,POST,DELETE
        # Command `gcloud --quiet beta run services replace` does not deploy new instance
        # unless this yaml is updated.
        # To force deploying new instance, add GH_SHA every time sources on GH is updated.
        - name: GH_SHA
          value: ${GITHUB_SHA}
