apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - image: gcr.io/blog-minilla/api:latest
        resources:
          limits:
            memory: 256Mi
            cpu: 1000m
        env:
        - name: GCP_PROJECT_ID
          value: blog-minilla
        - name: ENV
          value: minilla
        - name: ALLOWED_ORIGINS
          value: https://blog.tach.dev,http://localhost:4200
        - name: ALLOWED_METHODS
          value: GET,POST,DELETE