name: deploy-front-minilla

on:
  push:
    branches:
      - main
    tags:
      - qa

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: blog-minilla
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud builds submit --config=./front.minilla.cloudbuild.yaml
      - run: sudo apt-get install gettext-base
      - run: envsubst '${GITHUB_SHA}' < main_front/service-minilla.yaml > k.yaml
      - run: gcloud --quiet beta run services replace k.yaml --platform managed --region asia-northeast1