name: deploy-api-godzilla

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: suzuito-godzilla
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.GCP_PROJECT_ID}}
          service_account_key: ${{ secrets.GCP_SA_KEY_GODZILLA }}
          export_default_credentials: true
      - run: gcloud builds submit --config=./api.${{env.GCP_PROJECT_ID}}.cloudbuild.yaml
      - run: sudo apt-get install gettext-base
      - run: envsubst '${GITHUB_SHA}' < main_api/service-${{env.GCP_PROJECT_ID}}.yml > k.yaml
      - run: gcloud --quiet beta run services replace k.yaml --platform managed --region asia-northeast1
      - run: gsutil cors set gcs-cors-${{env.GCP_PROJECT_ID}}.json gs://${{env.GCP_PROJECT_ID}}-blog1-server
      - run: gsutil cors set gcs-cors-${{env.GCP_PROJECT_ID}}.json gs://${{env.GCP_PROJECT_ID}}-blog1-article