name: upload-minilla
on:
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: echo ${{ secrets.GCP_SA_KEY }} > cred.json
      - run: cat cred.json
      - run: export GOOGLE_APPLICATION_CREDENTIALS=./cred.json
      - run: go build main_uploader/main.go
      - run: source minilla.sh
      - run: env
      - run: ./main