name: upload-minilla
on:
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go build main_uploader/main.go
      - run: source minilla.sh
      - run: ./main